### ISSUE TITLE
Should we move this repo into libdparse?

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/DGrammar#7]
We could setup an automatic deployment job to gh-pages for libdparse and thus keep the generated `grammar.html`  always up-to-date.

**Comment by Hackerpilot** [comment]
I don't object to somebody other than me doing this work. :trollface:

**Comment by wilzbach** [comment]
Done: http://libdparse.dlang.io/grammar.html

I also setup automatic documentation deployment to gh-pages: http://libdparse.dlang.io

**Comment by wilzbach** [comment]
I will set the repo to "archive mode"
